# Generated by Django 5.0 on 2023-12-17 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                default="profile_photos/default_profile_photo.png",
                upload_to="profile_photos/",
            ),
        ),
        migrations.CreateModel(
            name="FinancialDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sales",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "ebitda",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "ebit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "pat",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("shares_issued", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "book_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("is_past_year", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ForecastedFinancialDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forecasted_sales",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "forecasted_ebitda",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "forecasted_ebit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "forecasted_pat",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_current_sales",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_current_pat",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
