# Generated by Django 5.0 on 2023-12-17 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0002_alter_customuser_profile_photo_financialdetails_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="forecastedfinancialdetails",
            name="id",
        ),
        migrations.AlterField(
            model_name="forecastedfinancialdetails",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="FinancialData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cmp_rs", models.FloatField()),
                ("pe", models.FloatField()),
                ("mar_cap_rs", models.FloatField()),
                ("no_of_shares", models.FloatField()),
                ("eps", models.FloatField()),
                ("net_earnings", models.FloatField()),
                ("sales_rs", models.FloatField()),
                ("sales_per_share", models.FloatField()),
                ("cmp_bv", models.FloatField()),
                ("bvps", models.FloatField()),
                ("bv_in_cr", models.FloatField()),
                ("ind_pe", models.FloatField()),
                ("ev_rs", models.FloatField()),
                ("pat_12m_rs", models.FloatField()),
                ("cmp_ocf", models.FloatField()),
                ("ocfps", models.FloatField()),
                ("ocf_in_cr", models.FloatField()),
                ("ev_ebitda", models.FloatField()),
                ("ebitdaps", models.FloatField()),
                ("ebitda_in_cr", models.FloatField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_auth.company",
                    ),
                ),
            ],
        ),
    ]
