# Generated by Django 3.2.13 on 2023-12-17 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_company_remove_forecastedfinancialdetails_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialdata',
            old_name='mar_cap_rs',
            new_name='mar_cap_rs_cr',
        ),
    ]
