# Generated by Django 3.2.17 on 2024-01-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_rename_mar_cap_rs_financialdata_mar_cap_rs_cr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialData',
        ),
    ]
