# Generated by Django 3.2.17 on 2024-01-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_auto_20240115_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdetails',
            name='industry',
            field=models.CharField(blank=True, choices=[('Primary Sector', 'Primary Sector'), ('Secondary Sector', 'Secondary Sector'), ('Emerging Industries', 'Emerging Industries')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='forecastedfinancialdetails',
            name='industry',
            field=models.CharField(blank=True, choices=[('Primary Sector', 'Primary Sector'), ('Secondary Sector', 'Secondary Sector'), ('Emerging Industries', 'Emerging Industries')], max_length=20, null=True),
        ),
    ]
