# Generated by Django 5.0 on 2024-01-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0007_auto_20240115_0706"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("cmp_rs", models.FloatField(blank=True, null=True)),
                ("pe", models.FloatField(blank=True, null=True)),
                ("market_cap_rs", models.FloatField(blank=True, null=True)),
                ("num_of_shares", models.FloatField(blank=True, null=True)),
                ("eps", models.FloatField(blank=True, null=True)),
                ("net_earnings_cr", models.FloatField(blank=True, null=True)),
                ("sales_rs", models.FloatField(blank=True, null=True)),
                ("sales_per_share", models.FloatField(blank=True, null=True)),
                ("cmp_over_bv", models.FloatField(blank=True, null=True)),
                ("bvps", models.FloatField(blank=True, null=True)),
                ("bv_in_cr", models.FloatField(blank=True, null=True)),
                ("ind_pe", models.FloatField(blank=True, null=True)),
                ("ev_rs", models.FloatField(blank=True, null=True)),
                ("pat_12m_rs", models.FloatField(blank=True, null=True)),
                ("cmp_over_ocf", models.FloatField(blank=True, null=True)),
                ("ocfps", models.FloatField(blank=True, null=True)),
                ("ocf_in_cr", models.FloatField(blank=True, null=True)),
                ("ev_over_ebitda", models.FloatField(blank=True, null=True)),
                ("ebitdaps", models.FloatField(blank=True, null=True)),
                ("ebitda_in_cr", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
