# Generated by Django 5.0 on 2024-01-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0008_financialdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialdata",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
