# Generated by Django 5.0 on 2024-01-31 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0010_formulavalue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormulaValue',
        ),
    ]
