# Generated by Django 5.0 on 2024-01-31 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0013_delete_company_remove_financialdata_bv_in_cr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormulaValue',
        ),
    ]
