# Generated by Django 5.0 on 2024-01-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0014_delete_formulavalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialdata',
            name='cmp_bv',
        ),
        migrations.RemoveField(
            model_name='financialdata',
            name='cmp_ocf',
        ),
        migrations.RemoveField(
            model_name='financialdata',
            name='ev_ebitda',
        ),
        migrations.AddField(
            model_name='financialdata',
            name='bv_in_cr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialdata',
            name='cmp_over_bv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialdata',
            name='cmp_over_ocf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialdata',
            name='cmp_over_sales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialdata',
            name='ev_over_ebitda',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialdata',
            name='num_of_shares',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialdata',
            name='sales_per_share',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='cmp_rs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='debt_eq',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='ev_rs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='ind_pe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='industry',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='mar_cap_rs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='np_qtr_rs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='pat_12m_rs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='pe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='profit_growth_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='roce_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='sales_qtr_rs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='sales_rs',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
