# Generated by Django 5.0 on 2024-01-31 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0015_remove_financialdata_cmp_bv_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialData',
        ),
    ]
