# Generated by Django 5.0 on 2024-01-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0016_delete_financialdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cmp_rs', models.FloatField(blank=True, default=0.0, null=True)),
                ('pe', models.FloatField(blank=True, default=0.0, null=True)),
                ('mar_cap_rs', models.FloatField(blank=True, default=0.0, null=True)),
                ('num_of_shares', models.FloatField(blank=True, default=0.0, null=True)),
                ('np_qtr_rs', models.FloatField(blank=True, default=0.0, null=True)),
                ('sales_qtr_rs', models.FloatField(blank=True, default=0.0, null=True)),
                ('roce_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('sales_rs', models.FloatField(blank=True, default=0.0, null=True)),
                ('sales_per_share', models.FloatField(blank=True, default=0.0, null=True)),
                ('cmp_over_sales', models.FloatField(blank=True, default=0.0, null=True)),
                ('cmp_over_bv', models.FloatField(blank=True, default=0.0, null=True)),
                ('bv_in_cr', models.FloatField(blank=True, default=0.0, null=True)),
                ('ind_pe', models.FloatField(blank=True, default=0.0, null=True)),
                ('profit_growth_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('ev_rs', models.FloatField(blank=True, default=0.0, null=True)),
                ('pat_12m_rs', models.FloatField(blank=True, default=0.0, null=True)),
                ('debt_eq', models.FloatField(blank=True, default=0.0, null=True)),
                ('cmp_over_ocf', models.FloatField(blank=True, default=0.0, null=True)),
                ('ev_over_ebitda', models.FloatField(blank=True, default=0.0, null=True)),
                ('industry', models.CharField(max_length=255)),
            ],
        ),
    ]
