# Generated by Django 5.0 on 2024-01-31 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0017_financialdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialData',
        ),
    ]
